import examplesFile from '../../public/examples/examples.json';
import n500Patent from '../../data/lenses/n500.json';
import d850Sensor from '../../data/d850.json';

const photo = examplesFile.examples.find(example => example.id === 'flycatcher')!;
const idealPupilMm = (n500Patent.focalLength / photo.fno).toFixed(1);
const readoutMs = d850Sensor.sensor.readout.electronicFullFrameMs.v;
const modelQuery = new URLSearchParams({ lens:photo.lens, fno:String(photo.fno), shutter:String(photo.shutter), iso:String(photo.iso), focus:String(photo.focusM), subject:String(photo.focusM), format:'ff' });
const modelLink = (piece:string, part?:string, lesson?:string) => {
  const query = new URLSearchParams(modelQuery); query.set('piece',piece);
  if(part) query.set('part',part); if(lesson) query.set('lesson',lesson);
  return './index.html?' + query;
};
const photoImage = `examples/${photo.image}`;
const svg = (label:string, body:string) => `<svg viewBox="0 0 640 280" role="img" aria-label="${label}" preserveAspectRatio="xMidYMid meet"><defs><linearGradient id="story-sky" x2="0" y2="1"><stop stop-color="#243c4c"/><stop offset="1" stop-color="#101a23"/></linearGradient><linearGradient id="story-glass-fill" x2="1"><stop stop-color="#67d9f8" stop-opacity=".12"/><stop offset=".5" stop-color="#bcefff" stop-opacity=".55"/><stop offset="1" stop-color="#67d9f8" stop-opacity=".12"/></linearGradient><clipPath id="story-photo-clip"><rect x="18" y="24" width="236" height="202" rx="8"/></clipPath><clipPath id="story-result-clip"><rect x="346" y="24" width="276" height="202" rx="8"/></clipPath></defs><rect x="1" y="1" width="638" height="278" rx="10" fill="url(#story-sky)" stroke="#314958"/><path d="M20 242H620" stroke="#7894a3" stroke-opacity=".22"/>${body}</svg>`;
const label = (value:string,x:number,y:number,anchor='middle') => `<text class="story-svg-label" x="${x}" y="${y}" text-anchor="${anchor}">${value}</text>`;
const photoPanel = `<image href="${photoImage}" x="18" y="24" width="236" height="202" preserveAspectRatio="xMidYMid slice" clip-path="url(#story-photo-clip)"/><rect x="18" y="24" width="236" height="202" rx="8" fill="none" stroke="#b7cfda" stroke-opacity=".55"/>`;
const lensSilhouette = `<path d="M350 77H534L554 91V190L534 204H350Z" fill="#0a131b" stroke="#728997" stroke-width="3"/><path d="M369 82V199M381 84V197M513 83V198" stroke="#425b68" stroke-width="5"/><path d="M403 88Q424 140 403 193M455 85Q478 140 455 196" fill="url(#story-glass-fill)" stroke="#7bdcff" stroke-width="3"/><path d="M560 105H594V177H560" fill="#182832" stroke="#9db3bd" stroke-width="3"/><path d="M571 109V173" stroke="#aaffde" stroke-width="3"/>`;
export const STORY_ARTWORK = {
  photo: svg('The supplied photograph shown beside a camera and sensor image plane', `${photoPanel}<path d="M286 117H330" stroke="#ffc16e" stroke-width="4"/><path d="M319 108L331 117L319 126" fill="none" stroke="#ffc16e" stroke-width="4"/>${lensSilhouette}<path d="M555 118L584 140L555 162" fill="none" stroke="#ffc16e" stroke-width="2"/><text class="story-svg-small" x="30" y="252">SUPPLIED JPEG</text>${label('Lens',451,226)}${label('Image plane',578,226)}`),
  light: svg('The actual bird photograph with illustrative light paths entering a lens', `${photoPanel}<circle cx="135" cy="105" r="18" fill="#ffc16e" fill-opacity=".2" stroke="#ffd58e"/><path d="M151 93L365 82M153 104L365 140M151 115L365 190" stroke="#ffc16e" stroke-width="2.5" stroke-dasharray="8 6"/><path d="M366 65Q390 140 366 207" fill="url(#story-glass-fill)" stroke="#7bdcff" stroke-width="4"/><path d="M394 73Q415 140 394 207" fill="url(#story-glass-fill)" stroke="#7bdcff" stroke-width="4"/><path d="M420 140H581" stroke="#ffc16e" stroke-width="2" stroke-dasharray="8 6"/><rect x="576" y="91" width="10" height="98" fill="#aaffde"/>${label('REFLECTED LIGHT · ILLUSTRATIVE',362,45,'start')}${label('Lens',393,235)}${label('Sensor',580,212)}`),
  lens: svg('A schematic lens cross-section with illustrative ray paths converging at the image plane', `<path d="M43 61H585V219H43" fill="#09141d" stroke="#627a88" stroke-width="2"/><path d="M52 69H579V211H52" fill="none" stroke="#304855" stroke-dasharray="5 7"/>${[160,225,315,382].map((x,i)=>`<path d="M${x} 77Q${x+22} 140 ${x} 203" fill="url(#story-glass-fill)" stroke="#81dcf7" stroke-width="3"/><path d="M${x+16} 81Q${x-3} 140 ${x+16} 199" fill="none" stroke="#a3edff" stroke-opacity=".7"/>`).join('')}<path d="M50 98L160 107L225 119L315 134L382 139L549 143M50 140L549 143M50 182L160 173L225 161L315 147L382 144L549 143" fill="none" stroke="#ffc16e" stroke-width="2.5"/><path d="M550 88V192" stroke="#aaffde" stroke-width="5"/>${label('SCHEMATIC LENS PATHS',52,45,'start')}${label('Curved glass groups',267,236)}${label('Image plane',552,215)}`),
  focus: svg('A bird subject and a background blur comparison show different blur sizes when focus is set', `${photoPanel}<path d="M286 77H357M286 143H357M286 208H357" stroke="#879eaa" stroke-dasharray="4 5"/><path d="M357 61Q383 143 357 225" fill="url(#story-glass-fill)" stroke="#73d9f4" stroke-width="3"/><path d="M386 75L541 143M386 143H541M386 211L541 143" stroke="#ffc16e" stroke-width="2.5"/><path d="M541 77V209" stroke="#aaffde" stroke-width="4"/><circle cx="541" cy="143" r="5" fill="#fff0be"/><ellipse cx="541" cy="186" rx="11" ry="22" fill="#c3a8ff" fill-opacity=".32" stroke="#c3a8ff" stroke-width="2"/>${label('FOCUSED SUBJECT',288,48,'start')}${label('Small spot',570,132)}${label('Background blur · comparison',490,235)}${label('Larger blur',570,190)}`),
  exposure: svg('A physical aperture and shutter timing control the light admitted to the sensor', `<circle cx="146" cy="137" r="78" fill="#101b24" stroke="#6a8291" stroke-width="3"/><circle cx="146" cy="137" r="56" fill="none" stroke="#7bdcff" stroke-opacity=".4" stroke-width="2"/><path d="M146 137L146 65Q180 72 190 98ZM146 137L207 102Q224 132 205 157ZM146 137L205 161Q187 195 153 208ZM146 137L145 209Q110 202 100 176ZM146 137L85 172Q68 142 87 117ZM146 137L87 113Q105 79 139 66Z" fill="#71cfe5" fill-opacity=".25" stroke="#71cfe5" stroke-width="2"/><circle cx="146" cy="137" r="24" fill="#0b141d" stroke="#b4ecfa" stroke-width="2"/><path d="M280 60V214M298 60V214" stroke="#aabfc8" stroke-width="6"/><path d="M306 214V60M324 214V60" stroke="#8ca5b1" stroke-width="6"/><path d="M221 137H380" stroke="#ffc16e" stroke-width="3" stroke-dasharray="8 7"/><path d="M350 124L381 137L350 150" fill="none" stroke="#ffc16e" stroke-width="3"/><path d="M402 207H589M402 207V72" stroke="#607985"/><path d="M411 183H581" stroke="#aaffde" stroke-width="7"/><path d="M411 196H581" stroke="#c3a8ff" stroke-width="7"/>${label('IRIS OPENING',146,246)}${label('CURTAIN TRAVEL',301,48)}${label('EXPOSURE WINDOW',500,236)}`),
  pixel: svg('A detailed sensor pixel cutaway with microlens, color filter, photodiode and charge well', `<path d="M76 67H564V220H76Z" fill="#0b151e" stroke="#8198a4" stroke-width="2"/><path d="M110 71Q320 -22 530 71" fill="#6cdef7" fill-opacity=".16" stroke="#9deeff" stroke-width="3"/><rect x="110" y="91" width="420" height="20" fill="#65d1ae" fill-opacity=".38" stroke="#6ce0ba"/><path d="M125 126V202H515V126" fill="#12605c" fill-opacity=".25" stroke="#51d4c1" stroke-width="3"/><path d="M180 17L232 91L310 142M320 17V142M460 17L408 91L330 142" stroke="#ffc16e" stroke-width="2.5" stroke-dasharray="7 6"/><circle cx="310" cy="157" r="8" fill="#d8ffe9"/><circle cx="350" cy="174" r="6" fill="#7ff5cd"/><circle cx="275" cy="184" r="5" fill="#9effda"/>${label('MICROLENS',320,51)}${label('COLOR FILTER',320,108)}${label('PHOTODIODE',320,151)}${label('COLLECTED CHARGE · SCHEMATIC',320,247)}`),
  readout: svg('Sensor rows scan into a signal converter and become digital samples', `<rect x="32" y="44" width="238" height="184" rx="5" fill="#0a151f" stroke="#637d8b" stroke-width="2"/>${Array.from({length:8},(_,r)=>Array.from({length:10},(_,c)=>`<rect x="${42+c*22}" y="${54+r*21}" width="19" height="18" fill="${r%2===0?(c%2===0?'#d17d86':'#76bd9c'):(c%2===0?'#76bd9c':'#6e9ed3')}" fill-opacity=".72" stroke="#d3e1e7" stroke-opacity=".12"/>`).join('')).join('')}<path d="M39 64H263" stroke="#fff1aa" stroke-width="4"/><path d="M286 135H361" stroke="#ffc16e" stroke-width="3"/><path d="M348 123L363 135L348 147" fill="none" stroke="#ffc16e" stroke-width="3"/><rect x="374" y="93" width="94" height="84" rx="8" fill="#10252d" stroke="#7ddfd0" stroke-width="2"/><path d="M391 151L410 127L427 143L449 112" fill="none" stroke="#aaffde" stroke-width="3"/><path d="M485 188V68M500 188V100M515 188V84M530 188V126M545 188V92M560 188V111M575 188V76M590 188V139" stroke="#b8a1ff" stroke-width="9"/><path d="M482 193H598" stroke="#8198a4"/>${label('ROW SCAN',150,251)}${label('SIGNAL',420,201)}${label('DIGITAL SAMPLES',540,224)}`),
  final: svg('The unchanged supplied JPEG beside illustrative color processing', `<image href="${photoImage}" x="346" y="24" width="276" height="202" preserveAspectRatio="xMidYMid slice" clip-path="url(#story-result-clip)"/><rect x="346" y="24" width="276" height="202" rx="8" fill="none" stroke="#b7cfda" stroke-opacity=".6"/><rect x="34" y="69" width="198" height="116" rx="8" fill="#0b151e" stroke="#667f8c" stroke-width="2"/><path d="M50 98H217M50 127H217M50 156H217" stroke="#ff9a89" stroke-width="11"/><path d="M253 127H316" stroke="#ffc16e" stroke-width="3"/><path d="M303 115L318 127L303 139" fill="none" stroke="#ffc16e" stroke-width="3"/><rect x="324" y="69" width="13" height="116" fill="#aaffde"/>${label('RGB DISPLAY CHANNELS',132,211)}${label('SUPPLIED JPEG · UNCHANGED',484,252)}`),
};

export const STORY_CHAPTERS = [
  {id:'photo',label:'The photo',title:'A sharp bird. A softer world.',copy:'Look at the bird, then the branches behind it. The camera turned light from different distances into different-sized spots. That difference helps the subject stand out.',figureValue:'500 mm',figureLabel:'recorded focal length',evidence:'Photo metadata',note:'This is Reed Osaki’s supplied JPEG. Its recorded settings anchor the story; the diagrams are illustrations.',action:'Play this photo’s journey',href:'./index.html?photo=flycatcher'},
  {id:'light',label:'Light',title:'The scene sends light in every direction.',copy:'Light reflects from the bird and the branches. A small part enters the lens. The opening determines how much of that light can join the image.',figureValue:`Ø ${idealPupilMm} mm`,figureLabel:'ideal pupil · 500 mm ÷ f/5.6',evidence:'Calculated from photo settings',note:'This ideal entrance-pupil diameter follows from the recorded nominal focal length and f-number. It is not a measurement of the photograph’s physical lens. The drawn paths are illustrative, not recovered rays or photon counts.',action:'Explore the camera',href:modelLink('camera')},
  {id:'lens',label:'Lens',title:'Glass changes the direction of light.',copy:'Each curved surface bends a ray. Together, the elements bring light toward the sensor. In the simulator, you can inspect paths traced through a published lens design.',figureValue:`${n500Patent.elements} elements · ${n500Patent.groups} groups`,figureLabel:'Nikon patent example · n500 model',evidence:'Published lens prescription',note:'The simulator uses this public patent example. The source documents a design representative of a commercial lens, not a verified prescription of the exact lens used for this photograph.',action:'Go inside the lens',href:modelLink('lens','glass')},
  {id:'focus',label:'Focus',title:'Sharpness belongs to a distance.',copy:'Light from the focused distance meets in a small spot at the sensor. Light from nearer or farther objects spreads into a blur disk. Change focus to move the sharp region through the scene.',figureValue:`≈ ${photo.focusM} m`,figureLabel:'camera-recorded focus distance',evidence:'Photo metadata · coarse steps',note:'The camera recorded focus in coarse steps. This image is not a depth map; the diagram is schematic.',action:'Try changing focus',href:modelLink('cone','focusRing')},
  {id:'exposure',label:'Exposure',title:'An opening, and a window of time.',copy:'The aperture limits the light admitted. The shutter limits how long it is collected. This photograph records f/5.6 and 1/4000 second. A shorter exposure can freeze motion, but gathers less light.',figureValue:`${(photo.shutter * 1000).toFixed(2)} ms`,figureLabel:'recorded shutter interval',evidence:'Calculated from photo metadata',note:'This duration is the recorded 1/4000-second shutter interval converted to milliseconds. ISO 1400 is also recorded. Raising ISO changes signal amplification; it creates no extra photons.',action:'Explore aperture and shutter',href:modelLink('camera','shutter')},
  {id:'pixel',label:'Pixel',title:'Light becomes an electrical signal.',copy:'Even equally lit pixels collect different numbers of photons: shot noise begins before electronics. A microlens and color filter guide light; some photons generate electrons that accumulate as signal.',figureValue:'6 photons / pixel',figureLabel:'expected count · controlled gray reference',evidence:'Computed experiment · not this photo',note:'The dim gray-reference experiment sets six expected incident photons per pixel so arrivals and shot noise are visible. Original sensor data is unavailable; this is not a count of photons or electrons from the photograph.',action:'Look inside a model pixel',href:modelLink('loupe','sensor')},
  {id:'readout',label:'Readout',title:'The camera measures the signal.',copy:'Readout turns accumulated charge into digital values. Timing determines when different rows are exposed and read. The electronic-scan lesson lets you explore why exposure time and scan time are different.',figureValue:`${readoutMs} ms`,figureLabel:'full-frame electronic scan · D850',evidence:'Reported bench measurement',note:`This ${readoutMs} ms timing is a reported full-frame electronic-shutter measurement on a tested Nikon D850. The new JPEG metadata identifies a Nikon D850, but shutter mode and original RAW samples are unavailable; do not attribute this electronic scan timing to the photograph.`,action:'Explore sensor readout',href:modelLink('camera','sensor','readout')},
  {id:'final',label:'The result',title:'Signals become a photograph.',copy:'Color reconstruction, white balance and display encoding help turn sensor samples into an image. Return to the bird: glass, focus and exposure all shaped the result you can see.',figureValue:'3 channels',figureLabel:'red · green · blue display output',evidence:'Display representation',note:'This is the supplied JPEG, not a reconstruction of its original raw data. The simulator’s separate image pipeline exposes its own calculated buffers.',action:'Explore the image pipeline',href:modelLink('camera','sensor','pipeline')},
] as const;

export function connectedStory(): string {
  return `<header class="story-heading"><p class="eyebrow">The story · Photon to Photo</p><h1>One moment.<br><span>Follow the light.</span></h1><p class="lede">Start with a real photograph. Follow what a camera does, from reflected light to a finished image.</p><div class="ref-actions"><a class="btn story-primary" href="./index.html?photo=flycatcher">Play photo journey →</a><a class="btn" href="./index.html?piece=camera" data-return-view>Explore the camera</a></div></header>
    <section class="connected-story" aria-label="Eight chapters from scene to photograph">
      <nav class="story-chapters" aria-label="Story chapters">${STORY_CHAPTERS.map((chapter,i)=>`<button type="button" data-story-chapter="${chapter.id}" aria-controls="story-chapter" ${i===0?'aria-current="step"':''}><span>${String(i+1).padStart(2,'0')}</span>${chapter.label}</button>`).join('')}</nav>
      <div class="story-spread"><figure class="story-photograph"><img src="examples/${photo.image}" width="1600" height="1066" alt="A vermilion flycatcher beside its nest, sharp against softer branches" fetchpriority="high"><figcaption><strong>${photo.title}</strong><span>Photo: Reed Osaki · Supplied JPEG</span></figcaption><div class="story-record"><span>Recorded</span><b>500 mm</b><b>f/5.6</b><b>1/4000 s</b><b>ISO 1400</b></div></figure>
        <article id="story-chapter" class="story-chapter" aria-labelledby="story-title"><div class="story-illustration" id="story-illustration"></div><div class="figure story-figure"><strong id="story-figure-value"></strong><small id="story-figure-label"></small><span class="figure-evidence" id="story-evidence"></span></div><h2 id="story-title"></h2><p id="story-copy"></p><details class="story-provenance"><summary>What backs this chapter</summary><p id="story-note"></p><a href="./reference.html?page=method">Method & limitations →</a></details><a class="btn" id="story-action"></a></article></div>
      <div class="story-transport"><button type="button" class="btn" id="story-prev">← Previous</button><p id="story-position" role="status"></p><button type="button" class="btn" id="story-next">Next chapter →</button></div>
    </section><p class="story-endnote">The photograph stays the same. The diagrams explain the journey. Follow a link at any chapter to experiment with the camera model.</p>`;
}

export function mountConnectedStory(): void {
  const buttons=[...document.querySelectorAll<HTMLButtonElement>('[data-story-chapter]')];
  let index=0;
  const show=(next:number,updateHash=true)=>{
    index=Math.max(0,Math.min(STORY_CHAPTERS.length-1,next)); const chapter=STORY_CHAPTERS[index];
    document.querySelector<HTMLVideoElement>('#story-illustration video')?.pause();
    document.getElementById('story-illustration')!.innerHTML=chapter.id==='pixel'?'<p class="story-loop-note">Computed gray-target experiment. These are not this photograph’s photons. Press Play to watch.</p><video controls loop muted playsinline preload="none" poster="media/photon-rain-poster.webp" aria-label="Six-second controlled gray-target photon arrival and noise experiment"><source src="media/photon-rain-loop.webm" type="video/webm">Equal light produces uneven photon counts.</video>':STORY_ARTWORK[chapter.id];
    document.getElementById('story-title')!.textContent=chapter.title;
    document.getElementById('story-copy')!.textContent=chapter.copy;
    document.getElementById('story-figure-value')!.textContent=chapter.figureValue;
    document.getElementById('story-figure-label')!.textContent=chapter.figureLabel;
    document.getElementById('story-evidence')!.textContent=chapter.evidence;
    document.getElementById('story-note')!.textContent=chapter.note;
    const action=document.getElementById('story-action') as HTMLAnchorElement;action.textContent=chapter.action+' →';action.href=chapter.href;
    document.getElementById('story-position')!.textContent=`${index+1} / ${STORY_CHAPTERS.length} · ${chapter.label}`;
    (document.getElementById('story-prev') as HTMLButtonElement).disabled=index===0;
    (document.getElementById('story-next') as HTMLButtonElement).disabled=index===STORY_CHAPTERS.length-1;
    buttons.forEach((button,i)=>i===index?button.setAttribute('aria-current','step'):button.removeAttribute('aria-current'));
    if(updateHash) history.replaceState(null,'',`#story-${chapter.id}`);
  };
  const fromHash=()=>{const found=STORY_CHAPTERS.findIndex(chapter=>location.hash===`#story-${chapter.id}`);show(found<0?0:found,false);};
  buttons.forEach((button,i)=>button.addEventListener('click',()=>show(i)));
  document.getElementById('story-prev')!.addEventListener('click',()=>show(index-1));
  document.getElementById('story-next')!.addEventListener('click',()=>show(index+1));
  document.addEventListener('visibilitychange',()=>{if(document.hidden)document.querySelector<HTMLVideoElement>('#story-illustration video')?.pause();});
  window.addEventListener('hashchange',fromHash);fromHash();
}
