import type { Model } from '../engine/model-types';

/** Read the same model as the photo; never infer a measurement from an animated decoration. */
export function learningInsights(m: Model) {
  const n = (v: number, digits = 1) => v.toLocaleString('en-US', { maximumFractionDigits: digits });
  const distance = (mm: number) => Number.isFinite(mm) ? `${n(mm / 1000, 2)} m` : '∞';
  return [
    { equation: 'E = hc/λ · photons carry energy; surfaces reflect a spectrum', live: `Modeled scene: ${n(m.exposure.sceneLux)} lux. An on-axis 18% gray patch sends about ${n(m.exposure.photonsMidGray)} photons to each physical pixel over this exposure.`, use: 'At dusk, a longer exposure or a wider aperture collects more photons. A tripod helps with camera movement; it cannot stop a moving subject.' },
    { equation: 'n₁ sin θ₁ = n₂ sin θ₂ · angles measured from the surface normal', live: `${m.lens.elements} elements in ${m.lens.groups} groups. Ray paths use each surface and its wavelength-dependent refractive index; Phase Fresnel surfaces also apply diffraction.`, use: 'Backlit branches and white lettering reveal color fringing. Glass dispersion separates wavelengths; combining elements helps bring them together. The spot inset shows where the traced colors land.' },
    { equation: 'N = f/D · nominal light ∝ t/N² · Airy radius ≈ 1.22λNworking', live: `Entrance pupil: ${n(2 * m.cardinal.ep.r, 2)} mm. Diffraction first-zero radius at ${n(m.diffraction.nm)} nm: ${n(m.diffraction.airyRadiusUm, 2)} µm (${n(m.diffraction.airyRadiusPx, 2)} sensor pixels).`, use: 'For a portrait, open the aperture to soften the background. For a landscape, stop down for depth of field—but very small openings spread each point through diffraction. One full stop halves the nominal light.' },
    { equation: '1/f ≈ 1/u + 1/v · a thin-lens guide; this view traces the full prescription', live: `Depth-of-field estimate: ${distance(m.focus.nearMm)}–${distance(m.focus.farMm)}, using a ${n(m.focus.cocMm * 1000, 1)} µm acceptable blur circle. This is a viewing convention, not an abrupt boundary.`, use: 'Focus on the eye in a portrait or a nearby bird. Move the point-distance slider to turn a sharp point into bokeh; compare the blur disk with the sensor’s pixel grid.' },
    { equation: '⟨e−⟩ = fill factor × Σ photonsλ QEλ · shot-noise σ = √⟨e−⟩', live: `18% gray expectation: ${n(m.exposure.electronsMidGray)} e−; modeled SNR ${n(m.exposure.snrMidGray)}. This ISO has ${n(m.sensor.readNoiseE, 2)} e− RMS read noise and ${n(m.sensor.fullWellE)} e− full well.`, use: 'In a dim room, raising ISO brightens the output but does not create photons. More captured light improves relative shot noise; bright windows can exceed charge or digital headroom.' },
    { equation: 'tstart(row) = row fraction × scan time · tend = tstart + exposure', live: `${n(m.sensor.readoutS * 1000, 2)} ms scan; ${n(m.scenario.shutter * 1000, 3)} ms per-row exposure. DN = clamp(round(black level + gain × electrons)), with noise added in the full sensor model.`, use: 'A fast shutter can freeze an athlete within each row while a slow electronic scan still bends a bat or leaning pole. Short exposure and fast readout solve different problems.' },
    { equation: 'Bayer → demosaic → white balance → color matrix → sRGB encoding', live: 'The image and magnified sample come from the current photo’s actual intermediate buffers. The wipe reveals stored results; it is not a simulation of processor scheduling.', use: 'Under warm room light, white balance adjusts channel gains. Fine fabric can challenge reconstruction; once a channel clips, later color processing cannot recover its lost detail.' },
    { equation: 'Motion blur ≈ |magnification| × transverse speed × exposure time', live: m.motion ? `This scene’s modeled motion streak: ${n(m.motion.blurPx, 2)} sensor pixels at ${n(m.motion.speedMps, 2)} m/s.` : 'The current subject is still. The Freeze motion experiment introduces a controlled 1 m/s moving target.', use: 'Try the same tradeoffs used for portraits, wildlife and night architecture: background separation, stopping action, and collecting more light. Pin A before changing a setting so the cost is visible.' },
  ];
}
